/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedOperationsRouteRouteImport } from './routes/_authed/operations/route'
import { Route as OperationsLoginRouteImport } from './routes/operations.login'
import { Route as AuthedOperationsIndexRouteImport } from './routes/_authed/operations/index'
import { Route as AuthedOperationsAccountsRouteImport } from './routes/_authed/operations/accounts'
import { Route as AuthedOperationsApprovalsRouteImport } from './routes/_authed/operations/approvals'
import { Route as AuthedOperationsAuditRouteImport } from './routes/_authed/operations/audit'
import { Route as AuthedOperationsCompletedTasksRouteImport } from './routes/_authed/operations/completed-tasks'
import { Route as AuthedOperationsContractorRouteImport } from './routes/_authed/operations/contractor'
import { Route as AuthedOperationsDispatchRouteImport } from './routes/_authed/operations/dispatch'
import { Route as AuthedOperationsEvidenceRouteImport } from './routes/_authed/operations/evidence'
import { Route as AuthedOperationsIncidentsRouteImport } from './routes/_authed/operations/incidents'
import { Route as AuthedOperationsKanbanRouteImport } from './routes/_authed/operations/kanban'
import { Route as AuthedOperationsMyTasksRouteImport } from './routes/_authed/operations/my-tasks'
import { Route as AuthedOperationsQcRouteImport } from './routes/_authed/operations/qc'
import { Route as AuthedOperationsReportsRouteImport } from './routes/_authed/operations/reports'
import { Route as AuthedOperationsSanitationRouteImport } from './routes/_authed/operations/sanitation'
import { Route as AuthedOperationsSecurityRouteImport } from './routes/_authed/operations/security'
import { Route as AuthedOperationsTriageRouteImport } from './routes/_authed/operations/triage'
import { Route as AuthedOperationsUnitsRouteImport } from './routes/_authed/operations/units'
import { Route as AuthedOperationsWorkOrdersRouteImport } from './routes/_authed/operations/work-orders'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOperationsRouteRoute = AuthedOperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const OperationsLoginRoute = OperationsLoginRouteImport.update({
  id: '/operations/login',
  path: '/operations/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOperationsIndexRoute = AuthedOperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsAccountsRoute =
  AuthedOperationsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsApprovalsRoute =
  AuthedOperationsApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsAuditRoute = AuthedOperationsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsCompletedTasksRoute =
  AuthedOperationsCompletedTasksRouteImport.update({
    id: '/completed-tasks',
    path: '/completed-tasks',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsContractorRoute =
  AuthedOperationsContractorRouteImport.update({
    id: '/contractor',
    path: '/contractor',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsDispatchRoute =
  AuthedOperationsDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsEvidenceRoute =
  AuthedOperationsEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsIncidentsRoute =
  AuthedOperationsIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsKanbanRoute = AuthedOperationsKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsMyTasksRoute = AuthedOperationsMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsQcRoute = AuthedOperationsQcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsReportsRoute = AuthedOperationsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsSanitationRoute =
  AuthedOperationsSanitationRouteImport.update({
    id: '/sanitation',
    path: '/sanitation',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsSecurityRoute =
  AuthedOperationsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)
const AuthedOperationsTriageRoute = AuthedOperationsTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsUnitsRoute = AuthedOperationsUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthedOperationsRouteRoute,
} as any)
const AuthedOperationsWorkOrdersRoute =
  AuthedOperationsWorkOrdersRouteImport.update({
    id: '/work-orders',
    path: '/work-orders',
    getParentRoute: () => AuthedOperationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedRouteWithChildren
  '/operations': typeof AuthedOperationsRouteRouteWithChildren
  '/operations/login': typeof OperationsLoginRoute
  '/operations/accounts': typeof AuthedOperationsAccountsRoute
  '/operations/approvals': typeof AuthedOperationsApprovalsRoute
  '/operations/audit': typeof AuthedOperationsAuditRoute
  '/operations/completed-tasks': typeof AuthedOperationsCompletedTasksRoute
  '/operations/contractor': typeof AuthedOperationsContractorRoute
  '/operations/dispatch': typeof AuthedOperationsDispatchRoute
  '/operations/evidence': typeof AuthedOperationsEvidenceRoute
  '/operations/incidents': typeof AuthedOperationsIncidentsRoute
  '/operations/kanban': typeof AuthedOperationsKanbanRoute
  '/operations/my-tasks': typeof AuthedOperationsMyTasksRoute
  '/operations/qc': typeof AuthedOperationsQcRoute
  '/operations/reports': typeof AuthedOperationsReportsRoute
  '/operations/sanitation': typeof AuthedOperationsSanitationRoute
  '/operations/security': typeof AuthedOperationsSecurityRoute
  '/operations/triage': typeof AuthedOperationsTriageRoute
  '/operations/units': typeof AuthedOperationsUnitsRoute
  '/operations/work-orders': typeof AuthedOperationsWorkOrdersRoute
  '/operations/': typeof AuthedOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedRouteWithChildren
  '/operations/login': typeof OperationsLoginRoute
  '/operations/accounts': typeof AuthedOperationsAccountsRoute
  '/operations/approvals': typeof AuthedOperationsApprovalsRoute
  '/operations/audit': typeof AuthedOperationsAuditRoute
  '/operations/completed-tasks': typeof AuthedOperationsCompletedTasksRoute
  '/operations/contractor': typeof AuthedOperationsContractorRoute
  '/operations/dispatch': typeof AuthedOperationsDispatchRoute
  '/operations/evidence': typeof AuthedOperationsEvidenceRoute
  '/operations/incidents': typeof AuthedOperationsIncidentsRoute
  '/operations/kanban': typeof AuthedOperationsKanbanRoute
  '/operations/my-tasks': typeof AuthedOperationsMyTasksRoute
  '/operations/qc': typeof AuthedOperationsQcRoute
  '/operations/reports': typeof AuthedOperationsReportsRoute
  '/operations/sanitation': typeof AuthedOperationsSanitationRoute
  '/operations/security': typeof AuthedOperationsSecurityRoute
  '/operations/triage': typeof AuthedOperationsTriageRoute
  '/operations/units': typeof AuthedOperationsUnitsRoute
  '/operations/work-orders': typeof AuthedOperationsWorkOrdersRoute
  '/operations': typeof AuthedOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/operations': typeof AuthedOperationsRouteRouteWithChildren
  '/operations/login': typeof OperationsLoginRoute
  '/_authed/operations/accounts': typeof AuthedOperationsAccountsRoute
  '/_authed/operations/approvals': typeof AuthedOperationsApprovalsRoute
  '/_authed/operations/audit': typeof AuthedOperationsAuditRoute
  '/_authed/operations/completed-tasks': typeof AuthedOperationsCompletedTasksRoute
  '/_authed/operations/contractor': typeof AuthedOperationsContractorRoute
  '/_authed/operations/dispatch': typeof AuthedOperationsDispatchRoute
  '/_authed/operations/evidence': typeof AuthedOperationsEvidenceRoute
  '/_authed/operations/incidents': typeof AuthedOperationsIncidentsRoute
  '/_authed/operations/kanban': typeof AuthedOperationsKanbanRoute
  '/_authed/operations/my-tasks': typeof AuthedOperationsMyTasksRoute
  '/_authed/operations/qc': typeof AuthedOperationsQcRoute
  '/_authed/operations/reports': typeof AuthedOperationsReportsRoute
  '/_authed/operations/sanitation': typeof AuthedOperationsSanitationRoute
  '/_authed/operations/security': typeof AuthedOperationsSecurityRoute
  '/_authed/operations/triage': typeof AuthedOperationsTriageRoute
  '/_authed/operations/units': typeof AuthedOperationsUnitsRoute
  '/_authed/operations/work-orders': typeof AuthedOperationsWorkOrdersRoute
  '/_authed/operations/': typeof AuthedOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/operations'
    | '/operations/login'
    | '/operations/accounts'
    | '/operations/approvals'
    | '/operations/audit'
    | '/operations/completed-tasks'
    | '/operations/contractor'
    | '/operations/dispatch'
    | '/operations/evidence'
    | '/operations/incidents'
    | '/operations/kanban'
    | '/operations/my-tasks'
    | '/operations/qc'
    | '/operations/reports'
    | '/operations/sanitation'
    | '/operations/security'
    | '/operations/triage'
    | '/operations/units'
    | '/operations/work-orders'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/operations/login'
    | '/operations/accounts'
    | '/operations/approvals'
    | '/operations/audit'
    | '/operations/completed-tasks'
    | '/operations/contractor'
    | '/operations/dispatch'
    | '/operations/evidence'
    | '/operations/incidents'
    | '/operations/kanban'
    | '/operations/my-tasks'
    | '/operations/qc'
    | '/operations/reports'
    | '/operations/sanitation'
    | '/operations/security'
    | '/operations/triage'
    | '/operations/units'
    | '/operations/work-orders'
    | '/operations'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/operations'
    | '/operations/login'
    | '/_authed/operations/accounts'
    | '/_authed/operations/approvals'
    | '/_authed/operations/audit'
    | '/_authed/operations/completed-tasks'
    | '/_authed/operations/contractor'
    | '/_authed/operations/dispatch'
    | '/_authed/operations/evidence'
    | '/_authed/operations/incidents'
    | '/_authed/operations/kanban'
    | '/_authed/operations/my-tasks'
    | '/_authed/operations/qc'
    | '/_authed/operations/reports'
    | '/_authed/operations/sanitation'
    | '/_authed/operations/security'
    | '/_authed/operations/triage'
    | '/_authed/operations/units'
    | '/_authed/operations/work-orders'
    | '/_authed/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  OperationsLoginRoute: typeof OperationsLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/operations/login': {
      id: '/operations/login'
      path: '/operations/login'
      fullPath: '/operations/login'
      preLoaderRoute: typeof OperationsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/operations/': {
      id: '/_authed/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthedOperationsIndexRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/accounts': {
      id: '/_authed/operations/accounts'
      path: '/accounts'
      fullPath: '/operations/accounts'
      preLoaderRoute: typeof AuthedOperationsAccountsRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/approvals': {
      id: '/_authed/operations/approvals'
      path: '/approvals'
      fullPath: '/operations/approvals'
      preLoaderRoute: typeof AuthedOperationsApprovalsRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/audit': {
      id: '/_authed/operations/audit'
      path: '/audit'
      fullPath: '/operations/audit'
      preLoaderRoute: typeof AuthedOperationsAuditRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/completed-tasks': {
      id: '/_authed/operations/completed-tasks'
      path: '/completed-tasks'
      fullPath: '/operations/completed-tasks'
      preLoaderRoute: typeof AuthedOperationsCompletedTasksRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/contractor': {
      id: '/_authed/operations/contractor'
      path: '/contractor'
      fullPath: '/operations/contractor'
      preLoaderRoute: typeof AuthedOperationsContractorRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/dispatch': {
      id: '/_authed/operations/dispatch'
      path: '/dispatch'
      fullPath: '/operations/dispatch'
      preLoaderRoute: typeof AuthedOperationsDispatchRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/evidence': {
      id: '/_authed/operations/evidence'
      path: '/evidence'
      fullPath: '/operations/evidence'
      preLoaderRoute: typeof AuthedOperationsEvidenceRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/incidents': {
      id: '/_authed/operations/incidents'
      path: '/incidents'
      fullPath: '/operations/incidents'
      preLoaderRoute: typeof AuthedOperationsIncidentsRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/kanban': {
      id: '/_authed/operations/kanban'
      path: '/kanban'
      fullPath: '/operations/kanban'
      preLoaderRoute: typeof AuthedOperationsKanbanRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/my-tasks': {
      id: '/_authed/operations/my-tasks'
      path: '/my-tasks'
      fullPath: '/operations/my-tasks'
      preLoaderRoute: typeof AuthedOperationsMyTasksRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/qc': {
      id: '/_authed/operations/qc'
      path: '/qc'
      fullPath: '/operations/qc'
      preLoaderRoute: typeof AuthedOperationsQcRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/reports': {
      id: '/_authed/operations/reports'
      path: '/reports'
      fullPath: '/operations/reports'
      preLoaderRoute: typeof AuthedOperationsReportsRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/sanitation': {
      id: '/_authed/operations/sanitation'
      path: '/sanitation'
      fullPath: '/operations/sanitation'
      preLoaderRoute: typeof AuthedOperationsSanitationRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/security': {
      id: '/_authed/operations/security'
      path: '/security'
      fullPath: '/operations/security'
      preLoaderRoute: typeof AuthedOperationsSecurityRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/triage': {
      id: '/_authed/operations/triage'
      path: '/triage'
      fullPath: '/operations/triage'
      preLoaderRoute: typeof AuthedOperationsTriageRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/units': {
      id: '/_authed/operations/units'
      path: '/units'
      fullPath: '/operations/units'
      preLoaderRoute: typeof AuthedOperationsUnitsRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
    '/_authed/operations/work-orders': {
      id: '/_authed/operations/work-orders'
      path: '/work-orders'
      fullPath: '/operations/work-orders'
      preLoaderRoute: typeof AuthedOperationsWorkOrdersRouteImport
      parentRoute: typeof AuthedOperationsRouteRoute
    }
  }
}

interface AuthedOperationsRouteRouteChildren {
  AuthedOperationsAccountsRoute: typeof AuthedOperationsAccountsRoute
  AuthedOperationsApprovalsRoute: typeof AuthedOperationsApprovalsRoute
  AuthedOperationsAuditRoute: typeof AuthedOperationsAuditRoute
  AuthedOperationsCompletedTasksRoute: typeof AuthedOperationsCompletedTasksRoute
  AuthedOperationsContractorRoute: typeof AuthedOperationsContractorRoute
  AuthedOperationsDispatchRoute: typeof AuthedOperationsDispatchRoute
  AuthedOperationsEvidenceRoute: typeof AuthedOperationsEvidenceRoute
  AuthedOperationsIncidentsRoute: typeof AuthedOperationsIncidentsRoute
  AuthedOperationsKanbanRoute: typeof AuthedOperationsKanbanRoute
  AuthedOperationsMyTasksRoute: typeof AuthedOperationsMyTasksRoute
  AuthedOperationsQcRoute: typeof AuthedOperationsQcRoute
  AuthedOperationsReportsRoute: typeof AuthedOperationsReportsRoute
  AuthedOperationsSanitationRoute: typeof AuthedOperationsSanitationRoute
  AuthedOperationsSecurityRoute: typeof AuthedOperationsSecurityRoute
  AuthedOperationsTriageRoute: typeof AuthedOperationsTriageRoute
  AuthedOperationsUnitsRoute: typeof AuthedOperationsUnitsRoute
  AuthedOperationsWorkOrdersRoute: typeof AuthedOperationsWorkOrdersRoute
  AuthedOperationsIndexRoute: typeof AuthedOperationsIndexRoute
}

const AuthedOperationsRouteRouteChildren: AuthedOperationsRouteRouteChildren = {
  AuthedOperationsAccountsRoute: AuthedOperationsAccountsRoute,
  AuthedOperationsApprovalsRoute: AuthedOperationsApprovalsRoute,
  AuthedOperationsAuditRoute: AuthedOperationsAuditRoute,
  AuthedOperationsCompletedTasksRoute: AuthedOperationsCompletedTasksRoute,
  AuthedOperationsContractorRoute: AuthedOperationsContractorRoute,
  AuthedOperationsDispatchRoute: AuthedOperationsDispatchRoute,
  AuthedOperationsEvidenceRoute: AuthedOperationsEvidenceRoute,
  AuthedOperationsIncidentsRoute: AuthedOperationsIncidentsRoute,
  AuthedOperationsKanbanRoute: AuthedOperationsKanbanRoute,
  AuthedOperationsMyTasksRoute: AuthedOperationsMyTasksRoute,
  AuthedOperationsQcRoute: AuthedOperationsQcRoute,
  AuthedOperationsReportsRoute: AuthedOperationsReportsRoute,
  AuthedOperationsSanitationRoute: AuthedOperationsSanitationRoute,
  AuthedOperationsSecurityRoute: AuthedOperationsSecurityRoute,
  AuthedOperationsTriageRoute: AuthedOperationsTriageRoute,
  AuthedOperationsUnitsRoute: AuthedOperationsUnitsRoute,
  AuthedOperationsWorkOrdersRoute: AuthedOperationsWorkOrdersRoute,
  AuthedOperationsIndexRoute: AuthedOperationsIndexRoute,
}

const AuthedOperationsRouteRouteWithChildren =
  AuthedOperationsRouteRoute._addFileChildren(
    AuthedOperationsRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedOperationsRouteRoute: typeof AuthedOperationsRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOperationsRouteRoute: AuthedOperationsRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  OperationsLoginRoute: OperationsLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
