import { PageToolbar } from "./PageToolbar";
import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Bot, Library, List, Network, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogBody, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { client } from "@/lib/client";
import { businessHeaders } from "@/lib/coordination/queries";
import { NewConnection } from "./Connections";
import { Skeleton } from "@/components/ui/skeleton";
import { managedAgentsQueryOptions, type AgentManagement, type ManagedAgent } from "@/lib/agent-management/queries";
import { createManagedAgentMutationOptions } from "@/lib/agent-management/mutations";
import { roomsQueryOptions } from "@/lib/rooms/queries";
import { queryClient } from "@/query-client";
import { AgentGraph } from "./AgentGraph";
import { AgentBuilder } from "./AgentBuilder";
import { AgentBadge, agentDisplayConfiguration, agentStanding, agentRole, serverLabel, toolDescription, toolLabel } from "./agent-display";
import "./agents.css";
export { agentStanding } from "./agent-display";

type View = "graph" | "list" | "library";
export function AgentsPage() {
  const initial = new URLSearchParams(window.location.search); const rooms = useQuery(roomsQueryOptions());
  const [chosen, setRoom] = useState(initial.get("room") || ""); const roomId = chosen || rooms.data?.items[0]?.id || "";
  const agents = useQuery(managedAgentsQueryOptions(roomId)); const create = useMutation(createManagedAgentMutationOptions(queryClient));
  const [selected, setSelected] = useState(initial.get("builder") || ""); const [view, setView] = useState<View>((initial.get("view") as View) || "graph");
  const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [createId, setCreateId] = useState(() => crypto.randomUUID()); const [search, setSearch] = useState("");
  const [mobile, setMobile] = useState(() => window.matchMedia?.("(max-width: 767px)").matches || false);
  useEffect(() => {const media = window.matchMedia?.("(max-width: 767px)"); if(!media) return; const change = () => setMobile(media.matches); media.addEventListener("change", change); return () => media.removeEventListener("change", change);}, []);
  function edit(id: string, nextRoom = roomId) {setSelected(id); const url = new URL(window.location.href); id ? url.searchParams.set("builder", id) : url.searchParams.delete("builder"); if(nextRoom) url.searchParams.set("room",nextRoom); window.history.replaceState(null,"",url);}
  useEffect(() => {const back = () => setSelected(new URLSearchParams(window.location.search).get("builder") || ""); window.addEventListener("popstate",back); return () => window.removeEventListener("popstate",back);}, []);
  const error = rooms.error || agents.error; const items = agents.data?.items || []; const open = items.find(a => a.id === selected);
  if(open && agents.data) return <AgentBuilder key={`${roomId}:${selected}`} roomId={roomId} agent={open} catalogue={agents.data} onClose={() => edit("")} />;
  return <div className="agents-page"><PageToolbar><header className="agents-toolbar"><h1>Agent</h1><div className="agent-segmented" aria-label="Cách xem agent">{([["graph","Sơ đồ",Network],["list","Danh sách",List],["library","Thư viện",Library]] as const).map(([key,label,Icon]) => <button key={key} type="button" aria-pressed={view === key} onClick={() => setView(key)}><Icon size={16} />{label}</button>)}</div><div className="agents-toolbar-end">{(rooms.data?.items.length || 0) > 1 && <Select value={roomId} onValueChange={value => {setRoom(value || ""); edit("", value || "");}}><SelectTrigger aria-label="Đơn vị"><SelectValue>{rooms.data?.items.find(r => r.id === roomId)?.name}</SelectValue></SelectTrigger><SelectContent>{rooms.data?.items.map(r => <SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select>}{agents.data?.canManage && <Button onClick={() => setCreating(true)}><Plus />Tạo agent</Button>}</div></header></PageToolbar>
    {error && <div className="agent-error" role="alert"><p>{error.message}</p><Button variant="outline" onClick={() => {void rooms.refetch(); void agents.refetch();}}>Thử lại</Button></div>}
    {rooms.isPending || (roomId && agents.isPending) ? <div className="agents-content"><Skeleton className="h-72" /></div> : !roomId ? <div className="agent-empty">Tài khoản chưa được thêm vào đơn vị. Liên hệ quản trị viên để được cấp quyền.</div> : agents.data && <>{view === "graph" && !mobile ? items.length ? <AgentGraph catalogue={agents.data} roomId={roomId} onEdit={edit} /> : <div className="agent-empty">Chưa có agent. Tạo agent để bắt đầu.</div> : <div className="agents-content">{mobile && view === "graph" && <p className="agent-hint">Sơ đồ được hiển thị dưới dạng danh sách trên điện thoại.</p>}{view === "library" ? <AgentLibrary catalogue={agents.data} roomId={roomId} /> : <><label className="agent-search"><Search size={16} /><Input aria-label="Tìm agent" placeholder="Tìm theo tên agent" value={search} onChange={e => setSearch(e.target.value)} /></label><AgentList items={items.filter(a => a.name.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi")))} catalogue={agents.data} roomId={roomId} onOpen={edit} /></>}</div>}</>}
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="ops-ui"><DialogHeader><DialogTitle>Tạo agent</DialogTitle><DialogDescription>Agent mới là bản nháp. Chạy thử và đánh giá trước khi phát hành.</DialogDescription></DialogHeader><DialogBody><label htmlFor="agent-name">Tên agent</label><Input id="agent-name" value={name} maxLength={160} onChange={e => setName(e.target.value)} />{create.error && <p role="alert">{create.error.message}</p>}</DialogBody><DialogFooter><Button variant="outline" disabled={create.isPending} onClick={() => setCreating(false)}>Hủy</Button><Button disabled={!name.trim() || create.isPending} onClick={async () => {try {const result = await create.mutateAsync({roomId,name:name.trim(),purpose:"specialist",requestId:createId}); setCreating(false);setName("");setCreateId(crypto.randomUUID());edit(result.id);} catch {}}}>{create.isPending ? "Đang tạo…" : "Tạo nháp"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function AgentList({items,catalogue,roomId,onOpen}: {items:ManagedAgent[];catalogue:AgentManagement;roomId:string;onOpen:(id:string)=>void}) {
 const graph=useQuery({queryKey:["agent-graph-list",roomId],refetchInterval:10000,queryFn:async()=> (await client(`/api/business/rooms/${encodeURIComponent(roomId)}/agent-graph`,{headers:businessHeaders(),fallback:"Không tải được số liệu agent."})).json() as Promise<{metrics:Record<string,{model_name?:string;seven_days:number;running:number}>}>});
 const [tab,setTab] = useState("published"); const group = (a:ManagedAgent) => a.published ? "published" : a.latest_version ? "revoked" : "draft";
 const rows = [...items].filter(a => group(a) === tab).sort((a,b) => Number(b.purpose === "supervisor") - Number(a.purpose === "supervisor") || a.name.localeCompare(b.name,"vi"));
 return <><div className="agent-list-tabs" role="tablist">{[["published","Đang phát hành"],["draft","Bản nháp"],["revoked","Đã thu hồi"]].map(([key,label]) => <button key={key} role="tab" aria-selected={tab === key} onClick={() => setTab(key)}>{label}<span>{items.filter(a => group(a) === key).length}</span></button>)}</div><div className="agent-table-wrap"><table className="agent-table"><thead><tr><th>Tên</th><th>Vai trò</th><th>Model</th><th>Khả năng</th><th>Bản đang phát hành</th><th>Phiên 7 ngày</th><th>Cập nhật</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(a => {const state = agentStanding(a); const config = agentDisplayConfiguration(a); return <tr key={a.id}><td><button className="agent-row-name" onClick={() => onOpen(a.id)}><span className="agent-icon-tile"><Bot size={16} /></span><span><strong>{a.name}</strong>{config.description && <small>{config.description}</small>}</span></button></td><td>{a.purpose === "supervisor" ? "Supervisor" : config.service_categories?.length ? "Tham gia phiên" : "Trả lời khi được hỏi"}</td><td>{graph.data?.metrics?.[a.id]?.model_name}</td><td>{config.mcp_tools?.length || 0} công cụ{config.skill_ids?.length ? `, ${config.skill_ids.length} kỹ năng` : ""}</td><td>{a.published && a.latest_version ? `Bản ${a.latest_version.number}` : "Chưa phát hành"}</td><td>{graph.data?.metrics?.[a.id]?.seven_days}</td><td>{a.updated_at && new Date(a.updated_at).toLocaleDateString("vi-VN")}</td><td><AgentBadge label={state.label} tone={state.tone} /></td></tr>;})}</tbody></table>{!rows.length && <div className="agent-empty">Không có agent trong mục này. Chọn mục khác hoặc tạo agent mới.</div>}</div></>;
}
function AgentLibrary({catalogue,roomId}: {catalogue:AgentManagement;roomId:string}) {
 const [tab,setTab] = useState("tools"); const [search,setSearch] = useState(""); const [addingConnection,setAddingConnection] = useState(false); const [addingSkill,setAddingSkill] = useState(false); const [skill,setSkill] = useState({name:"",description:"",instructions:""});
 const tools = catalogue.tools.filter(t => !t.external); const connections = useQuery({queryKey:["unit-connections",roomId],queryFn:async () => (await client(`/api/business/rooms/${encodeURIComponent(roomId)}/connections`,{headers:businessHeaders(),fallback:"Không tải được kết nối của đơn vị."})).json() as Promise<{items:{id:string;title:string;status:string;own:boolean;suspension_reason?:string;tools:{name:string;effect:string}[]}[]}>});
 const createSkill = useMutation({mutationFn:async () => {await client(catalogue.isAdmin ? "/api/business/admin/agent-skills" : `/api/business/rooms/${encodeURIComponent(roomId)}/agent-skills`,{method:"POST",body:skill,headers:businessHeaders(),fallback:"Không lưu được kỹ năng."});},onSuccess:async () => {await queryClient.invalidateQueries({queryKey:["managed-agents"]});setAddingSkill(false);setSkill({name:"",description:"",instructions:""});}});
 const check = useMutation({mutationFn:async (id:string) => (await client(`/api/business/rooms/${encodeURIComponent(roomId)}/connections/${encodeURIComponent(id)}/check`,{method:"POST",headers:businessHeaders(),fallback:"Không kiểm tra được kết nối."})).json() as Promise<{ok:boolean;error?:string}>,onSuccess:()=>queryClient.invalidateQueries({queryKey:["unit-connections",roomId]})});
 return <><div className="agent-library-toolbar"><div className="agent-list-tabs" role="tablist">{[["tools","Công cụ"],["skills","Kỹ năng"],["connections","Kết nối ngoài (MCP)"]].map(([key,label]) => <button role="tab" aria-selected={tab === key} key={key} onClick={() => setTab(key)}>{label}</button>)}</div><Input aria-label="Tìm trong thư viện" placeholder="Tìm trong thư viện" value={search} onChange={e => setSearch(e.target.value)} />{tab === "skills" && (catalogue.canManage || catalogue.isAdmin) && <Button onClick={() => setAddingSkill(true)}><Plus />{catalogue.isAdmin ? "Đăng kỹ năng dùng chung" : "Thêm kỹ năng"}</Button>}{tab === "connections" && catalogue.canManage && <Button onClick={() => setAddingConnection(true)}><Plus />Thêm kết nối</Button>}</div>
 <div className="agent-table-wrap"><table className="agent-table"><thead><tr><th>Tên</th><th>Mô tả</th><th>Thuộc về</th><th>Đang dùng bởi</th>{tab === "connections" && <th>Trạng thái</th>}</tr></thead><tbody>{tab === "tools" && tools.filter(t => toolLabel(t).toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi"))).map(t => <tr key={`${t.server_id}/${t.name}`}><td>{toolLabel(t)}</td><td>{toolDescription(t)}</td><td><span className="agent-owner-tag">Dùng chung</span></td><td>{catalogue.items.filter(a => agentDisplayConfiguration(a).mcp_tools?.some(g => g.name === t.name && g.server_id === t.server_id)).length} agent</td></tr>)}
 {tab === "skills" && catalogue.skills?.filter(s => s.name.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi"))).map(s => <tr key={s.id}><td>{s.name}</td><td>{s.description}</td><td><span className="agent-owner-tag">{s.workspace_id ? s.own ? "Bạn tạo" : "Đơn vị tạo" : "Dùng chung"}</span></td><td>{catalogue.items.filter(a => agentDisplayConfiguration(a).skill_ids?.includes(s.id)).length} agent</td></tr>)}
 {tab === "connections" && connections.data?.items.filter(c => c.title.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi"))).map(c => <tr key={c.id}><td>{c.title}</td><td>{c.tools.filter(t => t.effect === "read").length} đọc, {c.tools.filter(t => t.effect !== "read").length} ghi</td><td><span className="agent-owner-tag">{c.own ? "Bạn thêm" : "Quản trị viên cấp"}</span></td><td>{catalogue.items.filter(a => agentDisplayConfiguration(a).mcp_tools?.some(g => g.server_id === c.id)).length} agent</td><td><AgentBadge label={c.status === "suspended" ? "Tạm ngưng" : c.status === "pending" ? "Chờ duyệt" : "Đã kết nối"} tone={c.status === "suspended" ? "danger" : c.status === "pending" ? "wait" : "ok"} /><Button variant="ghost" size="sm" disabled={check.isPending} onClick={() => check.mutate(c.id)}>Kiểm tra</Button>{c.suspension_reason && <small>{c.suspension_reason}</small>}</td></tr>)}</tbody></table>
 {tab === "skills" && !catalogue.skills?.length && <div className="agent-empty">Chưa có kỹ năng. Thêm kỹ năng để dùng lại chỉ dẫn trên nhiều agent.</div>}{tab === "connections" && connections.isPending && <Skeleton className="h-24" />}{tab === "connections" && connections.error && <div role="alert" className="agent-error">{connections.error.message}<Button variant="outline" onClick={() => void connections.refetch()}>Thử lại</Button></div>}{tab === "connections" && connections.data && !connections.data.items.length && <div className="agent-empty">Chưa có kết nối ngoài. Thêm nguồn ngoài để cấp khả năng cho agent.</div>}{tab === "tools" && !tools.length && <div className="agent-empty">Chưa có công cụ được cấp cho đơn vị.</div>}</div>{check.error && <p role="alert" className="agent-error">{check.error.message}</p>}{check.data && <p role="status" className="agent-hint">{check.data.ok ? "Đã kiểm tra kết nối" : `Kết nối chưa hoạt động: ${check.data.error}`}</p>}
 {addingConnection && <NewConnection roomId={roomId} workspaces={[]} onClose={() => setAddingConnection(false)} />}
 <Dialog open={addingSkill} onOpenChange={setAddingSkill}><DialogContent className="ops-ui"><DialogHeader><DialogTitle>{catalogue.isAdmin ? "Đăng kỹ năng dùng chung" : "Thêm kỹ năng"}</DialogTitle><DialogDescription>Kỹ năng là chỉ dẫn có thể cấp cho nhiều agent. Bản đang phát hành giữ nguyên nội dung đã đánh giá.</DialogDescription></DialogHeader><DialogBody><label htmlFor="skill-name">Tên kỹ năng</label><Input id="skill-name" value={skill.name} maxLength={160} onChange={e => setSkill({...skill,name:e.target.value})} /><label htmlFor="skill-description">Mô tả</label><Input id="skill-description" value={skill.description} maxLength={2000} onChange={e => setSkill({...skill,description:e.target.value})} /><label htmlFor="skill-instructions">Chỉ dẫn</label><Textarea id="skill-instructions" rows={8} className="resize-none" maxLength={20000} value={skill.instructions} onChange={e => setSkill({...skill,instructions:e.target.value})} />{createSkill.error && <p role="alert">{createSkill.error.message}</p>}</DialogBody><DialogFooter><Button variant="outline" onClick={() => setAddingSkill(false)}>Hủy</Button><Button disabled={createSkill.isPending || !skill.name.trim() || !skill.instructions.trim()} onClick={() => createSkill.mutate()}>{createSkill.isPending ? "Đang lưu…" : "Lưu kỹ năng"}</Button></DialogFooter></DialogContent></Dialog>
 </>;
}
