"""Typed consumer proposals pending C13/C14/Platform approval; no route defaults.

Each producer verifies credentials and current scope/version/fence at remote apply.
Authorization references are backend issued, not minted by Coordination. Verification
ports include cryptographic/source validation in their trusted implementation.
"""
from typing import Protocol
from groupchat.ports import Invocation
from runtime.contributions import StaffContribution
from runtime.workflows import ContributionCommand,ReportCommand,WorkflowProof


class WorkflowAuthority(Protocol):
    async def verify_workflow(self, kind: str, command: ContributionCommand | ReportCommand,
                              exact_wire: dict, authentication: object, fence: int) -> dict: ...
    async def workflow_authentication(self, proof: WorkflowProof, authentication: object) -> object: ...
    async def report_invocation(self, command: ReportCommand, authentication: object, operation_id: str,
                                fence: int, instruction: str, artifact_hash: str) -> Invocation: ...


class ContributionProducer(Protocol):
    async def staff_request_for_work(self, state: object, delivery: object, authentication: object) -> dict | None: ...
    async def verify_staff_contribution(self, value: StaffContribution, authentication: object) -> dict: ...
    async def submit_contribution(self, value: StaffContribution, proof: dict) -> dict: ...
    async def reconcile_contribution(self, value: StaffContribution, proof: dict) -> dict | None: ...
    async def authorize_staff_request(self, command: ContributionCommand, authentication: object) -> dict: ...
    async def request_staff_contribution(self, command: ContributionCommand, proof: dict) -> dict: ...
    async def reconcile_staff_request(self, command: ContributionCommand, proof: dict) -> dict | None: ...
    async def authorize_contribution_status(self, command: ContributionCommand, authentication: object) -> dict: ...
    async def contribution_status(self, command: ContributionCommand, proof: dict) -> dict: ...


class ReportProducer(Protocol):
    async def authorize_report(self, config: dict, authentication: object) -> dict: ...
    async def create_report_request(self, intent: dict, authorization: dict) -> dict: ...
    async def reconcile_report_request(self, operation_id: str, authorization: dict) -> dict | None: ...
    async def fetch_report_snapshot(self, config: dict, authorization: dict) -> dict: ...
    async def authorize_report_request(self, request_id: str, authentication: object) -> dict: ...
    async def report_status(self, request_id: str, authorization: dict) -> dict: ...
    async def persist_report_result(self, intent: dict, authorization: dict) -> dict: ...
    async def reconcile_report_result(self, intent: dict, authorization: dict) -> dict | None: ...
    async def export_report(self, intent: dict, authorization: dict) -> dict: ...
    async def reconcile_report_export(self, intent: dict, authorization: dict) -> dict | None: ...
    async def cancel_report(self, intent: dict, authorization: dict) -> dict: ...
    async def reconcile_report_cancel(self, intent: dict, authorization: dict) -> dict | None: ...
    async def authorize_report_artifact(self, artifact_id: str, authentication: object) -> dict: ...
    # Returns async context manager of bounded bytes chunks, closes on cancellation.
    def stream_report_artifact(self, artifact_id: str, authorization: dict) -> object: ...
